### ISSUE TITLE
Uncaught TypeError: this.updateSideOrientation is not a function

### ISSUE THREAD

**Issue by lucasa** [brochington/akkad-boilerplate#1]
(unknown) Download the React DevTools for a better development experience: https://fb.me/react-devtools
(unknown) BJS - [14:15:35]: Babylon.js engine (v2.5) launched
localhost/:14 Uncaught TypeError: this.updateSideOrientation is not a function
    at new t.CreateBox (eval at <anonymous> (http://localhost:3032/static/bundle.js:1764:2), <anonymous>:14:7926)
    at Object.Box (eval at <anonymous> (http://localhost:3032/static/bundle.js:1758:2), <anonymous>:44280:17)
    at createShape (eval at <anonymous> (http://localhost:3032/static/bundle.js:1758:2), <anonymous>:44345:45)
    at StateManager.actionWrapper (eval at <anonymous> (http://localhost:3032/static/bundle.js:1758:2), <anonymous>:23705:34)
    at acc.(anonymous function) (eval at <anonymous> (http://localhost:3032/static/bundle.js:1758:2), <anonymous>:23607:49)
    at RenderShape.componentWillMount (eval at <anonymous> (http://localhost:3032/static/bundle.js:1758:2), <anonymous>:2262:14)
    at eval (eval at <anonymous> (http://localhost:3032/static/bundle.js:1074:2), <anonymous>:347:23)
    at measureLifeCyclePerf (eval at <anonymous> (http://localhost:3032/static/bundle.js:1074:2), <anonymous>:74:12)
    at ReactCompositeComponentWrapper.performInitialMount (eval at <anonymous> (http://localhost:3032/static/bundle.js:1074:2), <anonymous>:346:9)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (http://localhost:3032/static/bundle.js:1074:2), <anonymous>:257:21)
client.js?3ac5:67

**Comment by lucasa** [comment]
I got this error, any help?

**Comment by brochington** [comment]
@lucasa It's been a while since I've done any work on Akkad. Tonight I'll take a look and see if I can dust off some spiderwebs.
